export const GET_CHANNELS = "GET_CHANNELS";
export const GET_YTUBEDATA_SUCCESS = "GET_YTUBEDATA_SUCCESS";
export const GET_YTUBEDATA_REQUEST = "GET_YTUBEDATA_REQUEST";
export const GET_YTUBEDATA_FAILURE = "GET_YTUBEDATA_FAILURE";
